### ISSUE TITLE
Please add arm64 support

### ISSUE THREAD

**Issue by costarslam** [aviman1258/my-pal-json#7]
i could use this amd64 on my mac, but want to avoid qemu if possible. Thanks

**Comment by aviman1258** [comment]
Added arm64 support. Should run on both amd64 and arm64. @costarslam Please get latest from [dockerhub](https://hub.docker.com/repository/docker/achandra1258/my-pal-json/). Working on my machine. Can you please see if it is working on your mac.

**Comment by costarslam** [comment]
Thank you :)
